name: Deploy Docs

on:
  push:
    paths:
      - 'docs/**'
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Get Yarn Cache Directory
        id: yarn-cache
        run: |
          echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn Dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Yarn Dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./docs
      - name: Build Static
        run: yarn build
        working-directory: ./docs
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./docs/content/.vitepress/dist
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: devon.casthub.app
